---
- name: Gather Ansible Facts
  setup:

- name: Check if OS is supported
  include_tasks: os-check.yml

- name: Set Facts for Datadog Agent Major Version
  include_tasks: set-parse-version.yml

- name: Debian Install Tasks
  include_tasks: pkg-debian.yml
  when: ansible_facts.os_family == "Debian"

- name: Linux Configuration Tasks (Agent 5)
  include_tasks: agent5-linux.yml
  when: datadog_agent_major_version | int == 5 and ansible_facts.os_family != "Windows"

- name: Linux Configuration Tasks
  include_tasks: agent-linux.yml
  when: datadog_agent_major_version | int > 5 and ansible_facts.os_family != "Windows"
